openapi: 3.0.4
info:
  title: Hi-Lo The Game
  description: |
    This is a game in which clients can:
      - bet on a number beetween 1 and 100
      - receive a response:
        - hi, if the number is too high compared to the game specific number
        - lo, if it is low
        - correct if it is the secret number
  version: 0.0.1
paths:
  /games:
    post:
      summary: start a new game
      description: |
        Start a new game generating the
        secret number and return
        the created game id
      responses:
        "201":
          description: new game created
          content:
            application/json:
              schema:
                type: integer
    get:
      summary: list all games
      description: |
        Obtain the list of all games, with 
        the final result (win/lose) and
        the number of guesses
      responses:
        "200":
          description: |
            An array of objects, each containing
            the game id, the final outcome, and
            the number of guesses
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    outcome:
                      type: string
                      enum:
                        - win
                        - lose
                    guesses:
                      type: integer
                      
  /games/{id}:
    summary: a specific game
    parameters:
      - name: id
        in: path
        required: true
        description: this is the game id
        schema:
          type: integer
          description: "example: /games/1234"
    get:
      summary: get info on a game
      description: |
        Return a list of all guessess in reverse
        chronological order, including the responses
        received (hi/lo/correct)
      responses:
        "200":
          description: Request accepted, all guesses listed in content
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/guess-result"
    put:
      summary: reset a game
      description: |
        Start a game with given id, generating the secret
        number; or reset an existing game, re-generating the
        secret number and zeroing the guess counter
      responses:
        "200":
          description: An existing game is reset
        "201":
          description: A new game is created
    post:
      summary: place a guess
      description: |
        Try to guess the secret number; return hi, lo,
        or correct, plus the guess count
      parameters:
        - name: guess
          in: query
          required: true
          description: the guess
          schema:
            type: integer
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: Guess accepted, the result is in the content
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/guess-result"
        "403":
          description: game over
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  outcome:
                    type: string
                    enum:
                      - win
                      - lose
                  guesses:
                    type: integer
        "404":
          description: game not found

components:
  schemas:
    guess-result:
      type: object
      properties:
        guess-count:
          type: integer
          minimum: 1
          maximum: 10
        guess-outcome:
          type: string
          enum:
            - hi
            - lo
            - correct
      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
